name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        pg: [13, 12, 11, 10, 9.6, 9.5, 9.4, 9.3, 9.2]
    name: ğŸ˜ PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container:
      image: postgres:${{ matrix.pg }}
      options: -u postgres
    steps:
      - uses: actions/checkout@v1
      - run: initdb
      - run: pg_ctl start -l /tmp/server.log
      - run: apt-get -qq update && apt-get -qq install build-essential postgresql-server-dev-${{ matrix.pg }}
      - run: make
      - run: make install
      # - run: pg_isready
      - run: make installcheck PGUSER=postgres
